name: Feature Branch Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  backend-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package

      - name: Run Tests
        run: mvn test