name: Feature Pipeline

on:
  push:
    branches: "feature/*"
  pull_request:
    branches: "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create AccountKey.json
        env:
          ACCOUNT_KEY_JSON: ${{ secrets.ACCOUNT_KEY_JSON }}
        run: |
          echo "$ACCOUNT_KEY_JSON" > src/main/resources/AccountKey.json

      - name: Test with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn clean install