name: Feature Branch Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  frontend-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Run Tests
        run: npm test

  backend-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package

      - name: Run Tests
        run: mvn test