name: Main Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create AccountKey.json
        env:
          ACCOUNT_KEY_JSON: ${{ secrets.ACCOUNT_KEY_JSON }}
        run: |
          echo "$ACCOUNT_KEY_JSON" > src/main/resources/AccountKey.json

      - name: Build and Test
        run: mvn clean package